foundation: Open Neuroscience Foundation
title: Neuroscience Landscape
metadata_description: An interactive map of companies, organizations, laboratories, software and hardware tools, datasets, books, courses, podcasts, and more in the field of neuroscience.
metadata_keywords: landscape, neuroscience, research, brain-computer-interfaces, bci, industry, education, business, academia, tools, who-is-who, open-neuroscience-foundation
metadata_thumbnail: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/main/logo/onf-light-filled.png

url: https://neuroscience-landscape.com

analytics:
  gtm:
    container_id: G-XZ2BK3C8FR

colors:
  color1: "rgba(0, 107, 204, 1)" # Buttons, groups, links
  color2: "rgba(255, 0, 170, 1)" # Some highlighted items like filters button, search icon
  color3: "rgba(96, 149, 214, 1)" # Participation stats bars, spinners, modal titles
  color4: "rgba(0, 42, 81, 0.7)" # Categories titles in filters, fieldset in filters modal
  color5: "rgba(1, 107, 204, 0.7)" # Categories and subcategories frames (odd)
  color6: "rgba(0, 42, 81, 0.7)" # Categories and subcategories frames (even)

featured_items:
  - field: tag
    options:
      - value: hindex-100
        order: 2
        label: h-index 100+
  - field: tag
    options:
      - value: stars-4000
        order: 2
        label: 4K+ stars
      - value: stars-2000
        order: 3
        label: 2K+ stars
      - value: stars-1000
        order: 4
        label: 1K+ stars
      - value: stars-800
        order: 5
        label: 800+ stars
  - field: tag
    options:
      - value: most-used-book
        order: 6
        label: Major Reading
  - field: tag
    options:
      - value: largest-podcast
        order: 7
        label: Largest Podcast
  - field: tag
    options:
      - value: nobel-prize
        order: 1
        label: Nobel Prize

footer:
  links:
    github: https://github.com/open-neuroscience-foundation
  logo: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/main/logo/onf-title-light.png
  text: "Projects mentioned may or may not be affiliated with this foundation. Open Neuroscience Foundation. 2024"
  citation: |
    @software{Dubina_Neuroscience_Landscape_2024,
      author = {Dubina, Nikolay},
      license = {MIT},
      month = feb,
      title = {{Neuroscience Landscape}},
      url = {https://github.com/open-neuroscience-foundation/neuroscience-landscape},
      version = {2.1},
      year = {2024}
    }

grid_items_size: small

groups:
  - name: All categories
    categories:
      - Companies
      - Organizations
      - Laboratories
      - Software
      - Hardware
      - Datasets
      - Books
      - Courses
      - Podcasts
  - name: Laboratories
    categories:
      - Laboratories
  - name: Tools
    categories:
      - Software
      - Hardware
      - Datasets
  - name: Learning
    categories:
      - Books
      - Courses
      - Podcasts

header:
  links:
    github: https://github.com/open-neuroscience-foundation/neuroscience-landscape
  logo: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/main/logo/onf-title-dark.png

images:
  favicon: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/main/logo/onf-light-filled.png
  open_graph: https://raw.githubusercontent.com/open-neuroscience-foundation/.github/main/logo/onf-light-filled.png
